### ISSUE TITLE
Failure during fresh install

### ISSUE THREAD

**Issue by ukd1** [heroku/transferatu#39]
```
retinalols:transferatu russ$  heroku run bundle exec rake db:migrate
Running `bundle exec rake db:migrate` attached to terminal... up, run.3959
I, [2015-07-29T22:01:23.727855 #3]  INFO -- : [Rollbar] Scheduling payload
I, [2015-07-29T22:01:23.752674 #3]  INFO -- : [Rollbar] Sending payload
I, [2015-07-29T22:01:23.751835 #3]  INFO -- : [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=6b9c88fc-54d1-4ce4-a2be-13f82618de03 (only available if report was successful)
rake aborted!
missing=AT_REST_FERNET_SECRET
/app/vendor/bundle/ruby/2.2.0/gems/pliny-0.6.2/lib/pliny/config_helpers.rb:63:in `at_rest_fernet_secret'
/app/lib/models/group.rb:10:in `<class:Group>'
/app/lib/models/group.rb:2:in `<module:Transferatu>'
/app/lib/models/group.rb:1:in `<top (required)>'
/app/vendor/bundle/ruby/2.2.0/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require'
/app/vendor/bundle/ruby/2.2.0/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require_with_backports'
/app/vendor/bundle/ruby/2.2.0/gems/pliny-0.6.2/lib/pliny/utils.rb:23:in `block in require_glob'
/app/vendor/bundle/ruby/2.2.0/gems/pliny-0.6.2/lib/pliny/utils.rb:22:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/pliny-0.6.2/lib/pliny/utils.rb:22:in `require_glob'
/app/lib/initializer.rb:46:in `block in require!'
/app/lib/initializer.rb:45:in `each'
/app/lib/initializer.rb:45:in `require!'
/app/lib/initializer.rb:28:in `require_models'
/app/lib/initializer.rb:6:in `run'
/app/lib/initializer.rb:51:in `<top (required)>'
/app/vendor/bundle/ruby/2.2.0/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require'
/app/vendor/bundle/ruby/2.2.0/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require_with_backports'
/app/db/migrate/1407198907_fill_in_user_callback_password.rb:4:in `<top (required)>'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/extensions/migration.rb:716:in `load'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/extensions/migration.rb:716:in `block in get_migration_tuples'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/extensions/migration.rb:702:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/extensions/migration.rb:702:in `get_migration_tuples'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/extensions/migration.rb:639:in `initialize'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/extensions/migration.rb:391:in `new'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/extensions/migration.rb:391:in `run'
/app/vendor/bundle/ruby/2.2.0/gems/sequel-4.21.0/lib/sequel/extensions/migration.rb:362:in `apply'
/app/vendor/bundle/ruby/2.2.0/gems/pliny-0.6.2/lib/pliny/tasks/db.rake:13:in `block (3 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.2.0/gems/pliny-0.6.2/lib/pliny/tasks/db.rake:11:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/pliny-0.6.2/lib/pliny/tasks/db.rake:11:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
D, [2015-07-29T22:01:23.778418 #3] DEBUG -- : Terminating 3 actors...
W, [2015-07-29T22:01:23.779048 #3]  WARN -- : Terminating task: type=:call, meta={:method_name=>:perform}, status=:callwait
	Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
D, [2015-07-29T22:01:23.779236 #3] DEBUG -- : Celluloid::PoolManager: async call `perform` aborted!
Celluloid::Task::TerminatedError: task was terminated
	/app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:34:in `terminate'
	/app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `each'
	/app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `cleanup'
	/app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:329:in `shutdown'
	/app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:164:in `run'
	/app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
	/app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
	/app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
	/app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
	/app/vendor/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
W, [2015-07-29T22:01:23.779438 #3]  WARN -- : Terminating task: type=:finalizer, meta={:method_name=>:__shutdown__}, status=:receiving
	Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
W, [2015-07-29T22:01:23.946930 #3]  WARN -- : [Rollbar] Got unexpected status code from Rollbar api: 400
I, [2015-07-29T22:01:23.948560 #3]  INFO -- : [Rollbar] Response: {
  "err": 1,
  "message": "access token required"
}
retinalols:transferatu russ$ 

```

**Comment by ukd1** [comment]
@uhoh-itsmaciek these two PR's should fix it :+1:
